# Promtail configuration for Spikeformer log collection
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          source: attrs
          expressions:
            tag:
      - regex:
          source: tag
          expression: (?P<container_name>(?:[^|]*))\|(?P<image_name>(?:[^|]*))\|(?P<image_id>(?:[^|]*))\|(?P<container_id>(?:[^|]*))
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
          image_name:
          image_id:
          container_id:
      - output:
          source: output

  # Spikeformer application logs
  - job_name: spikeformer-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: spikeformer
          component: application
          __path__: /var/log/spikeformer/app.log
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - (?P<level>\w+) - (?P<logger>[\w.]+) - (?P<message>.*)'
      - timestamp:
          format: '2006-01-02 15:04:05,000'
          source: timestamp
      - labels:
          level:
          logger:

  # Neuromorphic hardware logs
  - job_name: neuromorphic-hardware
    static_configs:
      - targets:
          - localhost
        labels:
          job: spikeformer
          component: hardware
          __path__: /var/log/spikeformer/hardware/*.log
    pipeline_stages:
      - regex:
          expression: '/var/log/spikeformer/hardware/(?P<hardware_type>\w+)\.log'
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z) \[(?P<level>\w+)\] (?P<message>.*)'
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          level:
          hardware_type:

  # Model conversion logs
  - job_name: model-conversion
    static_configs:
      - targets:
          - localhost
        labels:
          job: spikeformer
          component: conversion
          __path__: /var/log/spikeformer/conversion.log
    pipeline_stages:
      - json:
          expressions:
            timestamp:
            level:
            model_id:
            conversion_step:
            message:
            duration_ms:
            accuracy:
            energy_ratio:
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          level:
          model_id:
          conversion_step:

  # Performance and benchmark logs
  - job_name: performance
    static_configs:
      - targets:
          - localhost
        labels:
          job: spikeformer
          component: performance
          __path__: /var/log/spikeformer/benchmark.log
    pipeline_stages:
      - json:
          expressions:
            timestamp:
            benchmark_type:
            model_name:
            hardware:
            batch_size:
            latency_ms:
            throughput:
            energy_uj:
            accuracy:
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          benchmark_type:
          model_name:
          hardware:

  # Error logs with special handling
  - job_name: spikeformer-errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: spikeformer
          component: errors
          severity: high
          __path__: /var/log/spikeformer/error.log
    pipeline_stages:
      - multiline:
          firstline: '^(ERROR|CRITICAL|FATAL)'
          max_wait_time: 5s
      - regex:
          expression: '^(?P<level>ERROR|CRITICAL|FATAL) (?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z) (?P<component>\w+): (?P<error_code>\w+) - (?P<message>.*)'
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          level:
          component:
          error_code:

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w{3} \d{1,2} \d{2}:\d{2}:\d{2}) (?P<hostname>\S+) (?P<process>\S+)(\[(?P<pid>\d+)\])?: (?P<message>.*)'
      - timestamp:
          format: 'Jan 2 15:04:05'
          source: timestamp
      - labels:
          hostname:
          process:
          pid: