apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spikeformer-advanced-hpa
  namespace: spikeformer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spikeformer-app
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
