apiVersion: apps/v1
kind: Deployment
metadata:
  name: spikeformer-app
  namespace: spikeformer
  labels:
    app: spikeformer
    component: neuromorphic-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spikeformer
  template:
    metadata:
      labels:
        app: spikeformer
    spec:
      containers:
        - name: spikeformer
          image: spikeformer-neuromorphic:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
