version: '3.8'

services:
  spikeformer:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    container_name: spikeformer-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NEUROMORPHIC_ENV=development
      - PYTHONPATH=/app
    volumes:
      - spikeformer-data:/app/data
      - spikeformer-logs:/app/logs
    networks:
      - spikeformer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  spikeformer-monitoring:
    image: prom/prometheus:latest
    container_name: spikeformer-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - spikeformer-network

  spikeformer-grafana:
    image: grafana/grafana:latest
    container_name: spikeformer-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    networks:
      - spikeformer-network

volumes:
  spikeformer-data:
  spikeformer-logs:
  prometheus-data:
  grafana-data:

networks:
  spikeformer-network:
    driver: bridge
