global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "quantum_consciousness_alerts.yml"

scrape_configs:
  - job_name: 'quantum-consciousness'
    static_configs:
      - targets: ['quantum-consciousness-service:80']
    scrape_interval: 10s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
